import { Link } from "react-router-dom";
import { ArrowLeft, Shield } from "lucide-react";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background font-inter">
      <div className="border-b border-border bg-card/50 backdrop-blur-md sticky top-0 z-30">
        <div className="max-w-3xl mx-auto px-6 h-14 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Shield className="w-5 h-5 text-xblue" />
            <span className="font-black text-white">Terms of Service</span>
          </div>
          <Link to="/" className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-white transition-colors">
            <ArrowLeft className="w-4 h-4" /> Home
          </Link>
        </div>
      </div>

      <main className="max-w-3xl mx-auto px-6 py-12 space-y-8">
        <div>
          <h1 className="text-3xl font-black text-white mb-2">Terms of Service</h1>
          <p className="text-muted-foreground text-sm">Last updated: April 21, 2026</p>
        </div>

        <div className="prose prose-invert max-w-none space-y-6 text-sm leading-relaxed text-muted-foreground">

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white">1. Acceptance of Terms</h2>
            <p>By accessing or using X Post Guardian Pro ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white">2. Description of Service</h2>
            <p>X Post Guardian Pro is an AI-powered content analysis and creation tool designed to help users create, analyze, and schedule content for the X (formerly Twitter) platform. The Service is not affiliated with, endorsed by, or officially connected to X Corp or Twitter, Inc.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white">3. User Responsibilities</h2>
            <p>You are solely responsible for all content you create, post, or schedule using the Service. You agree to:</p>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li>Comply with X's Terms of Service and Community Guidelines at all times</li>
              <li>Not use the Service to create spam, harassment, or abusive content</li>
              <li>Not use the Service to violate any applicable laws or regulations</li>
              <li>Not attempt to reverse engineer, hack, or disrupt the Service</li>
              <li>Take full responsibility for any content posted to X using outputs from this Service</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white">4. AI-Generated Content Disclaimer</h2>
            <p>The Service uses artificial intelligence to generate content suggestions. AI-generated content may not always be accurate, appropriate, or compliant with platform rules. You must review all AI-generated content before publishing. We make no guarantees that content generated by the Service will not result in account restrictions or suspensions on X.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white">5. X Platform Integration</h2>
            <p>The Service may integrate with the X API subject to X's Developer Agreement and Policy. Use of X-related features must comply with X's terms. We reserve the right to modify or discontinue X-related features at any time in response to changes in X's API policies.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white">6. Intellectual Property</h2>
            <p>Content you create using the Service remains your property. You grant us a limited license to process your content solely for the purpose of providing the Service. The Service's software, design, and underlying technology are owned by us and protected by intellectual property laws.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white">7. Disclaimer of Warranties</h2>
            <p>The Service is provided "as is" without warranties of any kind, express or implied. We do not warrant that the Service will be uninterrupted, error-free, or that AI analysis results will be accurate or complete.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white">8. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including any account actions taken by X against your account.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white">9. Changes to Terms</h2>
            <p>We reserve the right to modify these Terms at any time. Continued use of the Service after changes constitutes acceptance of the updated Terms.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white">10. Contact</h2>
            <p>For questions about these Terms of Service, please contact us through the app.</p>
          </section>
        </div>

        <div className="border-t border-border pt-6 flex gap-4 text-sm">
          <Link to="/privacy-policy" className="text-xblue hover:text-xblue/80 transition-colors">Privacy Policy →</Link>
          <Link to="/" className="text-muted-foreground hover:text-white transition-colors">Home</Link>
        </div>
      </main>
    </div>
  );
}